/* This file is auto-generated by Rake */

/* Build Host Info:
 * - Host Name: 0ced2af595d1
 * - Kernel Build: Linux version 5.4.0-80-generic (buildd@lcy01-amd64-030) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)) #90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021
 * - Build Timestamp: 2022-03-16 04:33:36 +0000
 * - Ruby Version: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
 * - Rake Version: rake, version 12.3.1
 */

/*
 * Source Control Info:
 * - Submodule:
 *    46483dc9d2929dcad019b0b89cb2dc12859d4979 emrun (segger/3.10.1-17-g46483dc)
 */

#ifndef __NUCLEI_SEGGER_RTL_RELEASE_H
#define __NUCLEI_SEGGER_RTL_RELEASE_H 1

#define __NUCLEI_SEGGER_RTL_RELEASE_COMMIT "5b650576558b13f47013332aff95841351d18189"

#endif /* __NUCLEI_SEGGER_RTL_RELEASE_H */
