/**
 * @file tkl_system.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "gd32vw55x.h"
#include "tkl_system.h"
#include "tuya_error_code.h"
#include "wrapper_os.h"
// --- END: user defines and implements ---

/**
 * @brief system reset
 *
 * @param none
 *
 * @return none
 */
void tkl_system_reset(void)
{
    // --- BEGIN: user implements ---
    SysTimer_SoftwareReset();
    return ;
    // --- END: user implements ---
}

/**
 * @brief Get system tick count
 *
 * @param none
 *
 * @return system tick count
 */
SYS_TICK_T tkl_system_get_tick_count(void)
{
    // --- BEGIN: user implements ---
    return sys_os_now(FALSE);
    // --- END: user implements ---
}

/**
 * @brief Get system millisecond
 *
 * @param none
 *
 * @return system millisecond
 */
SYS_TIME_T tkl_system_get_millisecond(void)
{
    // --- BEGIN: user implements ---
    return sys_time_get(NULL);
    // --- END: user implements ---
}

/**
 * @brief Get system random data
 *
 * @param[in] range: random from 0  to range
 *
 * @return random value
 */
int tkl_system_get_random(uint32_t range)
{
    // --- BEGIN: user implements ---
    uint32_t random_data = 0;

    if (!sys_random_bytes_get(&random_data, 4)) {
        return random_data % range;
    } else {
        return OPRT_COM_ERROR;
    }

    // --- END: user implements ---
}

/**
 * @brief Get system reset reason
 *
 * @param[in] describe: point to reset reason describe
 *
 * @return reset reason
 */
TUYA_RESET_REASON_E tkl_system_get_reset_reason(char **describe)
{
    // --- BEGIN: user implements ---
    /* The RCU reset flags stay set until software clears them, so latch them on the
     * first call and clear the hardware afterwards - otherwise a later reset would be
     * reported together with every earlier one. */
    static TUYA_RESET_REASON_E reason = TUYA_RESET_REASON_UNKNOWN;
    static const char *reason_str = "unknown";
    static uint8_t latched = 0;

    if (!latched) {
        /* most specific cause first: a power-on also raises the pin reset flag */
        if (SET == rcu_flag_get(RCU_FLAG_FWDGTRST)) {
            reason = TUYA_RESET_REASON_HW_WDOG;
            reason_str = "free watchdog";
        } else if (SET == rcu_flag_get(RCU_FLAG_WWDGTRST)) {
            reason = TUYA_RESET_REASON_SW_WDOG;
            reason_str = "window watchdog";
        } else if (SET == rcu_flag_get(RCU_FLAG_SWRST)) {
            reason = TUYA_RESET_REASON_SOFTWARE;
            reason_str = "software";
        } else if (SET == rcu_flag_get(RCU_FLAG_LPRST)) {
            reason = TUYA_RESET_REASON_DEEPSLEEP;
            reason_str = "low power";
        } else if (SET == rcu_flag_get(RCU_FLAG_PORRST)) {
            reason = TUYA_RESET_REASON_POWERON;
            reason_str = "power on";
        } else if (SET == rcu_flag_get(RCU_FLAG_EPRST)) {
            reason = TUYA_RESET_REASON_EXTERNAL;
            reason_str = "external pin";
        }

        rcu_all_reset_flag_clear();
        latched = 1;
    }

    if (describe) {
        *describe = (char *)reason_str;
    }

    return reason;
    // --- END: user implements ---
}

/**
 * @brief  system sleep
 *
 * @param[in] describe: num ms
 *
 * @return none
 */
void tkl_system_sleep(uint32_t num_ms)
{
    // --- BEGIN: user implements ---
    sys_ms_sleep(num_ms);
    return ;
    // --- END: user implements ---
}

/**
 * @brief system delay
 *
 * @param[in] msTime: time in MS
 *
 * @note This API is used for system sleep.
 *
 * @return void
 */
void tkl_system_delay(uint32_t num_ms)
{
    // --- BEGIN: user implements ---
    sys_ms_sleep(num_ms * OS_MS_PER_TICK);
    return ;
    // --- END: user implements ---
}

/**
 * @brief get system cpu info
 *
 * @param[in] cpu_ary: info of cpus
 * @param[in] cpu_cnt: num of cpu
 * @note This API is used for system cpu info get.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */

OPERATE_RET tkl_system_get_cpu_info(TUYA_CPU_INFO_T **cpu_ary, int *cpu_cnt)
{
    // --- BEGIN: user implements ---
    /* GD32VW553 is single core; the caller only reads the array, so a static one
     * avoids making it responsible for freeing anything. */
    static TUYA_CPU_INFO_T cpu_info;
    uint32_t stats_ms = 0, sleep_ms = 0;

    if (cpu_ary == NULL || cpu_cnt == NULL) {
        return OPRT_INVALID_PARM;
    }

    sys_cpu_sleep_time_get(&stats_ms, &sleep_ms);

    if (stats_ms > 0 && stats_ms >= sleep_ms) {
        cpu_info.use_ratio = ((stats_ms - sleep_ms) * 100U) / stats_ms;
    } else {
        cpu_info.use_ratio = 0;
    }

    /* the SDK exposes no accessor for a chip unique id, so report an empty one rather
     * than reading a guessed register address */
    cpu_info.chipidlen = 0;
    cpu_info.chipid[0] = '\0';

    *cpu_ary = &cpu_info;
    *cpu_cnt = 1;

    return OPRT_OK;
    // --- END: user implements ---
}

