/**
 * @file tkl_queue.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "wrapper_os.h"
#include "gd32vw55x.h"
#include "tkl_queue.h"
#include "tuya_error_code.h"
#include "riscv_encoding.h"
// --- END: user defines and implements ---

/**
 * @brief Create message queue
 *
 * @param[in] msgsize message size
 * @param[in] msgcount message number
 * @param[out] queue the queue handle created
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_queue_create_init(TKL_QUEUE_HANDLE *queue, int msgsize, int msgcount)
{
    // --- BEGIN: user implements ---
    if (NULL == queue) {
        return OPRT_OS_ADAPTER_INVALID_PARM;
    }

    if (!sys_queue_init(queue, msgcount, msgsize))
        return OPRT_OK;

    return OPRT_OS_ADAPTER_QUEUE_CREAT_FAILED;
    // --- END: user implements ---
}

/**
 * @brief post a message to the message queue
 *
 * @param[in] queue the handle of the queue
 * @param[in] data the data of the message
 * @param[in] timeout timeout time
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_queue_post(const TKL_QUEUE_HANDLE queue, void *data, uint32_t timeout)
{
    // --- BEGIN: user implements ---
    int ret;

    if (NULL == queue) {
        return OPRT_OS_ADAPTER_INVALID_PARM;
    }

    // Check if in interrupt context by reading RISC-V CSR_MSUBM register
    // MSUBM_TYP = 0x0100 (0x3<<6 with value 1) indicates interrupt context
    if ((__RV_CSR_READ(CSR_MSUBM) & MSUBM_TYP) == 0x40) {
        ret = sys_queue_write((os_queue_t *)&queue, data, 0, true);
    } else {
        ret = sys_queue_post_with_timeout((os_queue_t *)&queue, data, timeout);
    }

    if (ret) {
        return OPRT_OS_ADAPTER_QUEUE_SEND_FAIL;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief fetch message from the message queue
 *
 * @param[in] queue the message queue handle
 * @param[inout] msg the message fetch form the message queue
 * @param[in] timeout timeout time
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_queue_fetch(const TKL_QUEUE_HANDLE queue, void *msg, uint32_t timeout)
{
    // --- BEGIN: user implements ---
    void *dummyptr;
    int ret;

    if (NULL == queue) {
        return OPRT_OS_ADAPTER_INVALID_PARM;
    }

    if (msg == NULL) {
        msg = &dummyptr;
    }

    if (timeout == TKL_QUEUE_WAIT_FROEVER) {
        ret = sys_queue_fetch((os_queue_t *)&queue, msg, 0, TRUE);
    } else {
        ret = sys_queue_fetch((os_queue_t *)&queue, msg, timeout, (timeout == 0) ? FALSE : TRUE);
    }

    if (ret) {
        return OPRT_OS_ADAPTER_QUEUE_SEND_FAIL;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief free the message queue
 *
 * @param[in] queue the message queue handle
 *
 * @return void
 */
void tkl_queue_free(const TKL_QUEUE_HANDLE queue)
{
    // --- BEGIN: user implements ---
    if (NULL == queue) {
        return;
    }

    if (sys_queue_cnt((os_queue_t *)&queue)) {
        /* Line for breakpoint.  Should never break here! */
        __NOP();
    }

    sys_queue_free((os_queue_t *)&queue);
    return;
    // --- END: user implements ---
}
