/**
 * @file tkl_semaphore.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_semaphore.h"
#include "tuya_error_code.h"
#include "wrapper_os.h"
#include "gd32vw55x.h"

// --- END: user defines and implements ---

/**
 * @brief Create semaphore
 *
 * @param[out] handle: semaphore handle
 * @param[in] sem_cnt: semaphore init count
 * @param[in] sem_max: semaphore max count
 *
 * @note This API is used for creating semaphore.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_semaphore_create_init(TKL_SEM_HANDLE *handle, uint32_t sem_cnt, uint32_t sem_max)
{
    // --- BEGIN: user implements ---
    if (NULL == handle)
        return OPRT_OS_ADAPTER_INVALID_PARM;

    if ((!sys_sema_init_ext(handle, sem_max, sem_cnt)) && (NULL != handle)) {
        return OPRT_OK;
    } else {
        return OPRT_OS_ADAPTER_SEM_CREAT_FAILED;
    }
    // --- END: user implements ---
}

/**
 * @brief Wait semaphore
 *
 * @param[in] handle: semaphore handle
 * @param[in] timeout: wait timeout, bet: ms. SEM_WAIT_FOREVER means wait until get semaphore
 *
 * @note This API is used for waiting semaphore.
 *
 * @return OPRT_OK on success.OPRT_OS_ADAPTER_SEM_WAIT_TIMEOUT means timeout. Others on error, please refer to
 * tuya_error_code.h
 */
OPERATE_RET tkl_semaphore_wait(const TKL_SEM_HANDLE handle, uint32_t timeout)
{
    // --- BEGIN: user implements ---
    int32_t ret = 0;
    TKL_SEM_HANDLE local_handle = handle;

    if (NULL == handle)
        return OPRT_OS_ADAPTER_INVALID_PARM;

    if (timeout == TKL_SEM_WAIT_FOREVER) {
        ret = sys_sema_down((os_sema_t *)&local_handle, 0);
    } else {
        ret = sys_sema_down((os_sema_t *)&local_handle, timeout);
    }

    if (ret) {
        return OPRT_OS_ADAPTER_SEM_WAIT_FAILED;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Post semaphore
 *
 * @param[in] handle: semaphore handle
 *
 * @note This API is used for posting semaphore.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_semaphore_post(const TKL_SEM_HANDLE handle)
{
    // --- BEGIN: user implements ---
    TKL_SEM_HANDLE local_handle = handle;

    if (NULL == handle)
        return OPRT_OS_ADAPTER_SEM_POST_FAILED;

    if ((__RV_CSR_READ(CSR_MSUBM) & MSUBM_TYP) == 0x40) {
        sys_sema_up_from_isr((os_sema_t *)&local_handle);
    } else {
        sys_sema_up((os_sema_t *)&local_handle);
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Release semaphore
 *
 * @param[in] handle: semaphore handle
 *
 * @note This API is used for releasing semaphore.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_semaphore_release(const TKL_SEM_HANDLE handle)
{
    // --- BEGIN: user implements ---
    TKL_SEM_HANDLE local_handle = handle;

    if (NULL == handle)
        return OPRT_OS_ADAPTER_SEM_RELEASE_FAILED;

    sys_sema_free((os_sema_t *)&local_handle);
    return OPRT_OK;
    // --- END: user implements ---
}
