/**
 * @file tkl_watchdog.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "gd32vw55x.h"
#include "tkl_watchdog.h"
#include "wrapper_os.h"
#include "gd32vw55x_dbg.h"
#include "gd32vw55x_fwdgt.h"
#include "tuya_error_code.h"
// --- END: user defines and implements ---

/**
 * @brief watchdog init
 *
 * @param[in] cfg: watchdog config
 *
 * @return 0, init error; >0 : the actually watchdog interval
 */
uint32_t tkl_watchdog_init(TUYA_WDOG_BASE_CFG_T *cfg)
{
    // --- BEGIN: user implements ---
    uint8_t prescaler_div = FWDGT_PSC_DIV256;
    uint32_t actually_interval = cfg->interval_ms;
    uint16_t reload_value = 0;

    // enable IRC32K clock
    rcu_osci_on(RCU_IRC32K);
    rcu_osci_stab_wait(RCU_IRC32K);

    if (cfg->interval_ms >= 0 && cfg->interval_ms <= 511) {
        prescaler_div = FWDGT_PSC_DIV4;
        reload_value = cfg->interval_ms << 3;
    } else if (cfg->interval_ms >= 512 && cfg->interval_ms <= 1023) {
        prescaler_div = FWDGT_PSC_DIV8;
        reload_value = cfg->interval_ms << 2;
    } else if (cfg->interval_ms >= 1024 && cfg->interval_ms <= 2047) {
        prescaler_div = FWDGT_PSC_DIV16;
        reload_value = cfg->interval_ms << 1;
    } else if (cfg->interval_ms >= 2048 && cfg->interval_ms <= 4095) {
        prescaler_div = FWDGT_PSC_DIV32;
        reload_value = cfg->interval_ms;
    } else if (cfg->interval_ms >= 4096 && cfg->interval_ms <= 8190) {
        prescaler_div = FWDGT_PSC_DIV64;
        reload_value = cfg->interval_ms >> 1;
        actually_interval = cfg->interval_ms - (cfg->interval_ms & 0x01);
    } else if (cfg->interval_ms >= 8191 && cfg->interval_ms <= 16380) {
        prescaler_div = FWDGT_PSC_DIV128;
        reload_value = cfg->interval_ms >> 2;
        actually_interval = cfg->interval_ms - (cfg->interval_ms & 0x03);
    } else if (cfg->interval_ms >= 16381 && cfg->interval_ms <= 32760) {
        prescaler_div = FWDGT_PSC_DIV256;
        reload_value = cfg->interval_ms >> 3;
        actually_interval = cfg->interval_ms - (cfg->interval_ms & 0x07);
    } else {
        actually_interval = 32760;
        prescaler_div = FWDGT_PSC_DIV256;
        reload_value = 0xFFF;
    }

    fwdgt_config(reload_value, prescaler_div);
    while(FWDGT_STAT);
    fwdgt_enable();
    dbg_periph_enable(DBG_FWDGT_HOLD);

    return actually_interval;
    // --- END: user implements ---
}

/**
 * @brief watchdog deinit
 *
 * @param[in] none
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_watchdog_deinit(void)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED; // can not stop
    // --- END: user implements ---
}

/**
 * @brief refresh watch dog
 *
 * @param[in] none
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_watchdog_refresh(void)
{
    // --- BEGIN: user implements ---
    fwdgt_counter_reload();
    __NOP();
    __NOP();
    __NOP(); // to prevent enter deepsleep or standby mode

    return OPRT_OK;
    // --- END: user implements ---
}

