/**
 * @file tkl_hci.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "tkl_hci.h"
#include "tuya_error_code.h"

#include "virtual_hci.h"
#include "wrapper_os.h"
#include "ble_export.h"
#include "gd32vw55x_platform.h"

#ifdef CONFIG_ENABLE_HCI

#define TKL_BLE_STACK_TASK_STACK_SIZE    768

static os_sema_t tkl_hci_sema;

static void tkl_handle_event(uint8_t *p_header, uint16_t payload_length);
static void tkl_handle_acl_data(uint8_t *p_header, uint16_t payload_length);

static hci_recv_callback_t tkl_recv_cb = {
    tkl_handle_event,
    tkl_handle_acl_data,
    NULL,
    NULL,
};

static TKL_HCI_FUNC_CB hci_evt_callback = NULL;
static TKL_HCI_FUNC_CB acl_pkt_callback = NULL;

static void tkl_handle_event(uint8_t *p_header, uint16_t payload_length)
{
    uint8_t *pp = sys_malloc(payload_length + 2);

    if (pp == NULL || !virtual_hci_get_payload((pp + 2), payload_length)) {
        goto done;
    }

    sys_memcpy(pp, p_header, 2);
    if (hci_evt_callback) {
        hci_evt_callback(pp, (payload_length + 2));
    }
done:
    sys_mfree(pp);
}

static void tkl_handle_acl_data(uint8_t *p_header, uint16_t payload_length)
{
    uint8_t *pp = sys_malloc(payload_length + 4);

    if (pp == NULL || !virtual_hci_get_payload(pp + 4, payload_length)) {
        goto done;
    }

    sys_memcpy(pp, p_header, 4);
    if (acl_pkt_callback) {
        acl_pkt_callback(pp, (payload_length + 4));
    }

done:
    sys_mfree(pp);
}

// --- END: user defines and implements ---

/**
 * @brief   Function for initializing the bluetooth host-controller interface
 * @param   void
 * @return  SUCCESS             Initialized successfully.
 *          ERROR
 * */
OPERATE_RET tkl_hci_init(void)
{
    // --- BEGIN: user implements ---
    sys_sema_up(&tkl_hci_sema);
    return virtual_hci_send_command(HCI_RESET_CMD_OPCODE, 0, NULL) ? OPRT_OK : OPRT_OS_ADAPTER_BLE_INIT_FAILED;
    // --- END: user implements ---
}

/**
 * @brief   Function for de-initializing the bluetooth host-controller interface
 * @param   void
 * @return  SUCCESS             De-initialized successfully.
 *          ERROR
 * */
OPERATE_RET tkl_hci_deinit(void)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   [Linux/Android] Function for reseting the bluetooth host-controller interface
 *          Try to recover socket or reopen uart/usb interface.
 * @param   void
 * @return  SUCCESS             Reset successfully.
 *          ERROR
 * @note    [Special Interface] If running in RTOS, we may not support this feature.
 *          And you can report OPRT_NOT_SUPPORT if you dont need it.
 * */
OPERATE_RET tkl_hci_reset(void)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief   Send HCI-Command Packet to controller from host.
 *          The HCI Command packet is used to send commands to the Controller from
 *          the Host. The format of the HCI Command packet is shown @Rule
 *          Controllers shall be able to accept HCI Command packets with up to 255 bytes
 *          of data excluding the HCI Command packet header. The HCI Command packet
 *          header is the first 3 octets of the packet.
 *
 * @param   p_buf               Follow Core Spec. Refer to @Rule
 *          length              Indicate the length of the buffer. it can be "opcode + 1(len) + Parameter len";
 * @return  SUCCESS             Initialized successfully.
 *          ERROR
 *
 * @Spec    BLUETOOTH CORE SPECIFICATION Version 5.2 | Vol 4, Part E, 5-4.1
 * @Rule        2 bytes              1 byte              1 byte           N bytes
 *          OpCode(OCF+OGF) + Parameter Total Length + Parameter 0 ... + Parameter N
 * @Note    The OpCode Group Field (OGF), OpCode Command Field (OCF).
 * */
OPERATE_RET tkl_hci_cmd_packet_send(const uint8_t *p_buf, uint16_t buf_len)
{
    // --- BEGIN: user implements ---
    return virtual_hci_send_raw_data(HCI_CMD_MSG_TYPE, buf_len, (uint8_t *)p_buf) ? OPRT_OK : OPRT_OS_ADAPTER_BLE_HANDLE_ERROR;
    // --- END: user implements ---
}

/**
 * @brief   Send HCI-Command Packet to controller from host.
 *           HCI ACL Data packets are used to exchange data between the Host and Controller.
 *           Hosts and Controllers shall be able to accept HCI ACL Data packets with up to
 *           27 bytes of data excluding the HCI ACL Data packet header on
 *           Connection_Handles associated with an LE-U logical link.The HCI ACL Data
 *           packet header is the first 4 octets of the packet.
 *
 * @param   p_buf               Follow Core Spec. Refer to @Rule
 *          length              Indicate the length of the buffer. it can be "Handle + PB Flag
 *                              + PC Flag + Data Total Length";
 * @return  SUCCESS             Initialized successfully.
 *          ERROR
 *
 * @Spec    BLUETOOTH CORE SPECIFICATION Version 5.2 | Vol 4, Part E, 5-4.2
 * @Rule                                  2 bytes                             2 bytes         N bytes
 *          (Connection Handle + PB Flag(12-14bit) + PC Flag(14-16bit)) + Data Total Length + Data
 * @Note    PB Flag: Packet_Boundary_Flag; PB Flag: Broadcast_Flag;
 * */
OPERATE_RET tkl_hci_acl_packet_send(const uint8_t *p_buf, uint16_t buf_len)
{
    // --- BEGIN: user implements ---
    return virtual_hci_send_raw_data(HCI_ACL_MSG_TYPE, buf_len, (uint8_t *)p_buf) ? OPRT_OK : OPRT_OS_ADAPTER_BLE_HANDLE_ERROR;;
    // --- END: user implements ---
}

/**
 * @brief   Register the hci callback, while receiving "hci-event" or "acl-packet" data from controller,
 *          we will post these data into host stack.
 *          hci_evt_cb: The Host shall be able to accept HCI Event packets with up to 255 octets of data
 *          excluding the HCI Event packet header
 *          acl_pkt_cb: Refer to @tkl_hci_acl_packet_send
 *
 * @param   hci_evt_cb          Indicate the HCI Event callback.
 *          acl_pkt_cb          Indicate the ACL packet callback.
 * @return  SUCCESS             Initialized successfully.
 *          ERROR
 *
 * @Spec    BLUETOOTH CORE SPECIFICATION Version 5.2 | Vol 4, Part E, 5-4.4
 *          For More Event And Commnad Details:
 *          BLUETOOTH CORE SPECIFICATION Version 5.2 | Vol 4, Part E, 7-x
 *
 * @Rule    hci_evt_cb:
               1 byte        1 byte                1 byte                       N bytes
 *          Event Code + Parameter Total Length+ Event Parameter 0 + ... + Event Parameter N
 * */
OPERATE_RET tkl_hci_callback_register(const TKL_HCI_FUNC_CB hci_evt_cb, const TKL_HCI_FUNC_CB acl_pkt_cb)
{
    // --- BEGIN: user implements ---
    hci_evt_callback = hci_evt_cb;

    acl_pkt_callback = acl_pkt_cb;

    return OPRT_OK;
    // --- END: user implements ---
}

void tkl_virtual_hci_init(void)
{
    ble_init_param_t param = {0};

    ble_os_api_t os_interface = {
      .os_malloc = sys_malloc,
      .os_calloc = sys_calloc,
      .os_mfree = sys_mfree,
      .os_memset = sys_memset,
      .os_memcpy = sys_memcpy,
      .os_memcmp = sys_memcmp,
      .os_task_create = sys_task_create,
      .os_task_init_notification = sys_task_init_notification,
      .os_task_wait_notification = sys_task_wait_notification,
      .os_task_notify = sys_task_notify,
      .os_task_delete = sys_task_delete,
      .os_ms_sleep = sys_ms_sleep,
      .os_current_task_handle_get = sys_current_task_handle_get,
      .os_queue_init = sys_queue_init,
      .os_queue_free = sys_queue_free,
      .os_queue_write = sys_queue_write,
      .os_queue_read = sys_queue_read,
      .os_random_bytes_get = sys_random_bytes_get,
    };

    sys_sema_init(&tkl_hci_sema, 0);

    ble_power_on();

    param.ble_task_stack_size = TKL_BLE_STACK_TASK_STACK_SIZE;
    param.ble_task_priority = OS_TASK_PRIORITY(2);
    param.en_cfg = 0;
    param.p_os_api = &os_interface;

    virtual_hci_init(tkl_recv_cb, &param.p_hci_uart_func);

    ble_sw_init(&param);
    /* The BLE interrupt must be enabled after ble_sw_init. */
    ble_irq_enable();
}

void tkl_wait_ble_ready(void)
{
    sys_sema_down(&tkl_hci_sema, 0);
}

#endif
