/**
 * @file tkl_network.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "lwip/sockets.h"
#include "lwip/netdb.h"
#include "lwip/errno.h"
#include "wrapper_os.h"
#include "debug_print.h"
#include "tkl_network.h"
#include "tkl_system.h"
#include "tkl_output.h"
#include "tuya_error_code.h"
// --- END: user defines and implements ---

#define UNW_TO_SYS_FD_SET(fds)  ((fd_set*)fds)

typedef struct NETWORK_ERRNO_TRANSFER {
    int sys_err;
    int priv_err;
}ERRNO_TRANSFER;

const ERRNO_TRANSFER unw_network_errno_transfer[]= {
    {EINTR,         UNW_EINTR},
    {EBADF,         UNW_EBADF},
    {EAGAIN,        UNW_EAGAIN},
    {ENOMEM,        UNW_ENOMEM},
    {EFAULT,        UNW_EFAULT},
    {EBUSY,         UNW_EBUSY},
    {EINVAL,        UNW_EINVAL},
    {ENFILE,        UNW_ENFILE},
    {EMFILE,        UNW_EMFILE},
    {ENOSPC,        UNW_ENOSPC},
    {EPIPE,         UNW_EPIPE},
    {EWOULDBLOCK,   UNW_EWOULDBLOCK},
    {ENOTSOCK,      UNW_ENOTSOCK},
    {ENOPROTOOPT,   UNW_ENOPROTOOPT},
    {EADDRINUSE,    UNW_EADDRINUSE},
    {EADDRNOTAVAIL, UNW_EADDRNOTAVAIL},
    {ENETDOWN,      UNW_ENETDOWN},
    {ENETUNREACH,   UNW_ENETUNREACH},
    {ENETRESET,     UNW_ENETRESET},
    {ECONNRESET,    UNW_ECONNRESET},
    {ENOBUFS,       UNW_ENOBUFS},
    {EISCONN,       UNW_EISCONN},
    {ENOTCONN,      UNW_ENOTCONN},
    {ETIMEDOUT,     UNW_ETIMEDOUT},
    {ECONNREFUSED,  UNW_ECONNREFUSED},
    {EHOSTDOWN,     UNW_EHOSTDOWN},
    {EHOSTUNREACH,  UNW_EHOSTUNREACH},
    {EMSGSIZE,      UNW_EMSGSIZE}
};

/**
 * @brief Get error code of network
 *
 * @param void
 *
 * @note This API is used for getting error code of network.
 *
 * @return 0 on success. Others on error, please refer to the error no of the target system
 */
TUYA_ERRNO tkl_net_get_errno(void)
{
    int i = 0;
    int sys_err = errno;

    for (i = 0; i < (int)sizeof(unw_network_errno_transfer) / sizeof(unw_network_errno_transfer[0]); i++) {
        if (unw_network_errno_transfer[i].sys_err == sys_err) {
            // printf("%s:errno1:%d\r\n", __func__, unw_network_errno_transfer[i].sys_err);
            return unw_network_errno_transfer[i].priv_err;
        }
    }
    // printf("%s:errno2:%d\r\n",__func__,-100 - sys_err);

    return -100 - sys_err;
}

/**
 * @brief Add file descriptor to set
 *
 * @param[in] fd: file descriptor
 * @param[in] fds: set of file descriptor
 *
 * @note This API is used to add file descriptor to set.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_fd_set(const int fd, TUYA_FD_SET_T *fds)
{
    // --- BEGIN: user implements ---
    if ((fd < 0) || (fds == NULL)) {
        return -3000 + fd;
    }

    FD_SET(fd, UNW_TO_SYS_FD_SET(fds));

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Clear file descriptor from set
 *
 * @param[in] fd: file descriptor
 * @param[in] fds: set of file descriptor
 *
 * @note This API is used to clear file descriptor from set.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_fd_clear(const int fd, TUYA_FD_SET_T *fds)
{
    // --- BEGIN: user implements ---
    if ((fd < 0) || (fds == NULL)) {
        return -3000 + fd;
    }

    FD_CLR(fd, UNW_TO_SYS_FD_SET(fds));
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Check file descriptor is in set
 *
 * @param[in] fd: file descriptor
 * @param[in] fds: set of file descriptor
 *
 * @note This API is used to check the file descriptor is in set.
 *
 * @return TRUE or FALSE
 */
OPERATE_RET tkl_net_fd_isset(const int fd, TUYA_FD_SET_T *fds)
{
    // --- BEGIN: user implements ---
    if ((fd < 0) || (fds == NULL)) {
        return -3000 + fd;
    }

    return FD_ISSET(fd, UNW_TO_SYS_FD_SET(fds));
    // --- END: user implements ---
}

/**
 * @brief Clear all file descriptor in set
 *
 * @param[in] fds: set of file descriptor
 *
 * @note This API is used to clear all file descriptor in set.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_fd_zero(TUYA_FD_SET_T *fds)
{
    // --- BEGIN: user implements ---
    if (fds == NULL) {
        return 0xFFFFFFFF;
    }

    FD_ZERO(UNW_TO_SYS_FD_SET(fds));

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Get available file descriptors
 *
 * @param[in] maxfd: max count of file descriptor
 * @param[out] readfds: a set of readalbe file descriptor
 * @param[out] writefds: a set of writable file descriptor
 * @param[out] errorfds: a set of except file descriptor
 * @param[in] ms_timeout: time out
 *
 * @note This API is used to get available file descriptors.
 *
 * @return >0 the count of available file descriptors, <=0 error.
 */
int tkl_net_select(const int maxfd, TUYA_FD_SET_T *readfds, TUYA_FD_SET_T *writefds, TUYA_FD_SET_T *errorfds,
                   const uint32_t ms_timeout)
{
    // --- BEGIN: user implements ---
    if (maxfd <= 0) {
        return -3000 + maxfd;
    }

    struct timeval *tmp = NULL;
    struct timeval timeout = {ms_timeout / 1000, (ms_timeout % 1000) * 1000};

    if (0 != ms_timeout) {
        tmp = &timeout;
    } else {
        tmp = NULL;
    }

    return select(maxfd, UNW_TO_SYS_FD_SET(readfds), UNW_TO_SYS_FD_SET(writefds), UNW_TO_SYS_FD_SET(errorfds), tmp);
    // --- END: user implements ---
}

/**
 * @brief Get no block file descriptors
 *
 * @param[in] fd: file descriptor
 *
 * @note This API is used to get no block file descriptors.
 *
 * @return >0 the count of no block file descriptors, <=0 error.
 */
int tkl_net_get_nonblock(const int fd)
{
    // --- BEGIN: user implements ---
    if (fd < 0) {
        return -3000 + fd;
    }

    if ((fcntl(fd, F_GETFL, 0) & O_NONBLOCK) != O_NONBLOCK) {
        return 0;
    }

    if (errno == EAGAIN || errno == EWOULDBLOCK) {
        return 1;
    }

    return 0;
    // --- END: user implements ---
}

/**
 * @brief Set block flag for file descriptors
 *
 * @param[in] fd: file descriptor
 * @param[in] block: block flag
 *
 * @note This API is used to set block flag for file descriptors.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_set_block(const int fd, const BOOL_T block)
{
    // --- BEGIN: user implements ---
    if (fd < 0) {
        return -3000 + fd;
    }

    int flags;

    flags = fcntl(fd, F_GETFL, 0);
    if (block) {
        flags &= (~O_NONBLOCK);
    } else {
        flags |= O_NONBLOCK;
    }

    if (fcntl(fd, F_SETFL, flags) < 0) {
        return OPRT_MID_TRANSPORT_SOCK_SET_BLOCK_FAILED;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Close file descriptors
 *
 * @param[in] fd: file descriptor
 *
 * @note This API is used to close file descriptors.
 *
 * @return 0 on success. Others on error, please refer to the error no of the target system
 */
TUYA_ERRNO tkl_net_close(const int fd)
{
    // --- BEGIN: user implements ---
    if (fd < 0) {
        return -3000 + fd;
    }

    return close(fd);
    // --- END: user implements ---
}

/**
 * @brief Shutdown file descriptors
 *
 * @param[in] fd: file descriptor
 * @param[in] how: shutdown type
 *
 * @note This API is used to shutdown file descriptors.
 *
 * @return 0 on success. Others on error, please refer to the error no of the target system
 */
TUYA_ERRNO tkl_net_shutdown(const int fd, const int how)
{
    // --- BEGIN: user implements ---
    if (fd < 0) {
        return -3000 + fd;
    }

    return shutdown(fd, how);
    // --- END: user implements ---
}

/**
 * @brief Create a tcp/udp socket
 *
 * @param[in] type: protocol type, tcp or udp
 *
 * @note This API is used for creating a tcp/udp socket.
 *
 * @return file descriptor
 */
int tkl_net_socket_create(const TUYA_PROTOCOL_TYPE_E type)
{
    // --- BEGIN: user implements ---
    int32_t fd = -1;

    switch (type) {
    case PROTOCOL_TCP:
        fd = socket(PF_INET, SOCK_STREAM, IPPROTO_TCP);
        break;
    case PROTOCOL_UDP:
        fd = socket(AF_INET, SOCK_DGRAM, 0);
        break;
    case PROTOCOL_RAW:
        fd = socket(AF_INET, SOCK_RAW, IPPROTO_ICMP);
        break;
    default:
        break;
    }

    return fd;
    // --- END: user implements ---
}

/**
 * @brief Connect to network
 *
 * @param[in] fd: file descriptor
 * @param[in] addr: address information of server
 * @param[in] port: port information of server
 *
 * @note This API is used for connecting to network.
 *
 * @return 0 on success. Others on error, please refer to the error no of the target system
 */
TUYA_ERRNO tkl_net_connect(const int fd, const TUYA_IP_ADDR_T addr, const uint16_t port)
{
    // --- BEGIN: user implements ---
    if (fd < 0) {
        return -3000 + fd;
    }

    struct sockaddr_in sock_addr = {0};
    unsigned short tmp_port = port;
    TUYA_IP_ADDR_T tmp_addr = addr;

    sock_addr.sin_family = AF_INET;
    sock_addr.sin_port = htons(tmp_port);
    sock_addr.sin_addr.s_addr = htonl(tmp_addr);

    return connect(fd, (struct sockaddr *)&sock_addr, sizeof(struct sockaddr_in));
    // --- END: user implements ---
}

/**
 * @brief Connect to network with raw data
 *
 * @param[in] fd: file descriptor
 * @param[in] p_socket: raw socket data
 * @param[in] len: data lenth
 *
 * @note This API is used for connecting to network with raw data.
 *
 * @return 0 on success. Others on error, please refer to the error no of the target system
 */
TUYA_ERRNO tkl_net_connect_raw(const int fd, void *p_socket_addr, const int len)
{
    // --- BEGIN: user implements ---
    if (fd < 0) {
        return -3000 + fd;
    }

    return connect(fd, (struct sockaddr *)p_socket_addr, len);
    // --- END: user implements ---
}

/**
 * @brief Bind to network
 *
 * @param[in] fd: file descriptor
 * @param[in] addr: address information of server
 * @param[in] port: port information of server
 *
 * @note This API is used for binding to network.
 *
 * @return 0 on success. Others on error, please refer to the error no of the target system
 */
TUYA_ERRNO tkl_net_bind(const int fd, const TUYA_IP_ADDR_T addr, const uint16_t port)
{
    // --- BEGIN: user implements ---
    if (fd < 0) {
        return -3000 + fd;
    }

    int ret = 0;
    unsigned short tmp_port = port;
    TUYA_IP_ADDR_T tmp_addr = addr;
    struct sockaddr_in sock_addr = {0};

    sock_addr.sin_family = AF_INET;
    sock_addr.sin_len = sizeof(sock_addr);
    sock_addr.sin_port = htons(tmp_port);
    sock_addr.sin_addr.s_addr = htonl(tmp_addr);

    ret = bind(fd, (struct sockaddr *)&sock_addr, sizeof(sock_addr));

    return ret == 0 ? OPRT_OK : OPRT_MID_TRANSPORT_SOCK_NET_BIND_FAILED ;
    // --- END: user implements ---
}

/**
 * @brief Listen to network
 *
 * @param[in] fd: file descriptor
 * @param[in] backlog: max count of backlog connection
 *
 * @note This API is used for listening to network.
 *
 * @return 0 on success. Others on error, please refer to the error no of the target system
 */
TUYA_ERRNO tkl_net_listen(const int fd, const int backlog)
{
    // --- BEGIN: user implements ---
    if (fd < 0) {
        return -3000 + fd;
    }

    return listen(fd, backlog);
    // --- END: user implements ---
}

/**
 * @brief Listen to network
 *
 * @param[in] fd: file descriptor
 * @param[out] addr: the accept ip addr
 * @param[out] port: the accept port number
 *
 * @note This API is used for listening to network.
 *
 * @return 0 on success. Others on error, please refer to the error no of the target system
 */
TUYA_ERRNO tkl_net_accept(const int fd, TUYA_IP_ADDR_T *addr, uint16_t *port)
{
    // --- BEGIN: user implements ---
    if (fd < 0) {
        return -3000 + fd;
    }

    struct sockaddr_in sock_addr = {0};
    socklen_t len = sizeof(struct sockaddr_in);
    int ret = accept(fd, (struct sockaddr *)&sock_addr, &len);
    if (ret < 0) {
        return OPRT_COM_ERROR;
    }

    if (addr) {
        *addr = ntohl((sock_addr.sin_addr.s_addr));
    }

    if (port) {
        *port = ntohs((sock_addr.sin_port));
    }

    return ret;
    // --- END: user implements ---
}

/**
 * @brief Send data to network
 *
 * @param[in] fd: file descriptor
 * @param[in] buf: send data buffer
 * @param[in] nbytes: buffer lenth
 *
 * @note This API is used for sending data to network
 *
 * @return >0 on num of send, <0 please refer to the error no of the target system
 */
TUYA_ERRNO tkl_net_send(const int fd, const void *buf, const uint32_t nbytes)
{
    // --- BEGIN: user implements ---
    if ((fd < 0) || (buf == NULL) || (nbytes == 0)) {
        return -3000 + fd;
    }

    return send(fd, buf, nbytes, 0);
    // --- END: user implements ---
}

/**
 * @brief Send data to specified server
 *
 * @param[in] fd: file descriptor
 * @param[in] buf: send data buffer
 * @param[in] nbytes: buffer lenth
 * @param[in] addr: address information of server
 * @param[in] port: port information of server
 *
 * @note This API is used for sending data to network
 *
 * @return >0 on num of send, <0 please refer to the error no of the target system
 */
TUYA_ERRNO tkl_net_send_to(const int fd, const void *buf, const uint32_t nbytes, const TUYA_IP_ADDR_T addr,
                           const uint16_t port)
{
    // --- BEGIN: user implements ---
    if ((fd < 0) || (buf == NULL) || (nbytes == 0)) {
        return -3000 + fd;
    }

    int ret = -1;

    unsigned short tmp_port = port;
    TUYA_IP_ADDR_T tmp_addr = addr;

    struct sockaddr_in sock_addr = {0};
    sock_addr.sin_family = AF_INET;
    sock_addr.sin_len = sizeof(struct sockaddr_in);
    sock_addr.sin_port = htons(tmp_port);
    sock_addr.sin_addr.s_addr = htonl(tmp_addr);

    ret = sendto(fd, buf, nbytes, 0, (struct sockaddr *)&sock_addr, sizeof(sock_addr));

    return ret;
    // --- END: user implements ---
}

/**
 * @brief Receive data from network
 *
 * @param[in] fd: file descriptor
 * @param[in] buf: receive data buffer
 * @param[in] nbytes: buffer lenth
 *
 * @note This API is used for receiving data from network
 *
 * @return >0 on num of recv, <0 please refer to the error no of the target system
 */
TUYA_ERRNO tkl_net_recv(const int fd, void *buf, const uint32_t nbytes)
{
    // --- BEGIN: user implements ---
    if ((fd < 0) || (buf == NULL) || (nbytes == 0)) {
        return -3000 + fd;
    }

    int flags = fcntl(fd, F_GETFL, 0);
    int noblock = flags & O_NONBLOCK;

    if (!noblock) {
        fd_set set;
        FD_ZERO(&set);
        FD_SET(fd, &set);
        if (select(fd + 1, &set, NULL, NULL, NULL) < 0) {
            return -1;
        }
    }

    return recv(fd, buf, nbytes, 0);
    // --- END: user implements ---
}

/**
 * @brief Receive data from network with need size
 *
 * @param[in] fd: file descriptor
 * @param[in] buf: receive data buffer
 * @param[in] nbytes: buffer lenth
 * @param[in] nd_size: the need size
 *
 * @note This API is used for receiving data from network with need size
 *
 * @return >0 on success. Others on error
 */
int tkl_net_recv_nd_size(const int fd, void *buf, const uint32_t buf_size, const uint32_t nd_size)
{
    // --- BEGIN: user implements ---
    int recv_size = 0;
    int ret = 0;

    if((fd < 0) || (buf == NULL) || (buf_size == 0) || (nd_size == 0) || (buf_size < nd_size)) {
        return -3000 + fd;
    }

    while (recv_size < nd_size) {
        ret = recv(fd, (uint8_t *)(buf + recv_size), nd_size - recv_size, 0);
        if (ret <= 0) {
            TUYA_ERRNO err = tkl_net_get_errno();
            if (EWOULDBLOCK == err || \
                    EINTR == err || \
                    EAGAIN == err) {
                tkl_system_sleep(10);
                continue;
            }
            break;
        }
        recv_size += ret;
    }

    if (recv_size < nd_size) {
        return UNW_FAIL;
    }

    return recv_size;
    // --- END: user implements ---
}

/**
 * @brief Receive data from specified server
 *
 * @param[in] fd: file descriptor
 * @param[in] buf: receive data buffer
 * @param[in] nbytes: buffer lenth
 * @param[in] addr: address information of server
 * @param[in] port: port information of server
 *
 * @note This API is used for receiving data from specified server
 *
 * @return >0 on num of recv, <0 please refer to the error no of the target system
 */
TUYA_ERRNO tkl_net_recvfrom(const int fd, void *buf, const uint32_t nbytes, TUYA_IP_ADDR_T *addr, uint16_t *port)
{
    // --- BEGIN: user implements ---
    if ((fd < 0) || (buf == NULL) || (nbytes == 0)) {
        return -3000 + fd;
    }

    int ret = 0;
    struct sockaddr_in saddr = {0};
    socklen_t len = sizeof(struct sockaddr_in);

    ret = recvfrom(fd, buf, nbytes, 0, (struct sockaddr *)&saddr, &len);

    if (ret <= 0) {
        return OPRT_RECV_ERR;
    }

    if (addr) {
        *addr = ntohl(saddr.sin_addr.s_addr);
    }

    if (port) {
        *port = ntohs(saddr.sin_port);
    }

    return ret;
    // --- END: user implements ---
}

/**
 * @brief Get address information by domain
 *
 * @param[in] domain: domain information
 * @param[in] addr: address information
 *
 * @note This API is used for getting address information by domain.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_gethostbyname(const char *domain, TUYA_IP_ADDR_T *addr)
{
    // --- BEGIN: user implements ---
    if ((domain == NULL) || (addr == NULL)) {
        return OPRT_OS_ADAPTER_INVALID_PARM;
    }

    struct hostent *h = NULL;

    if ((h = gethostbyname(domain)) == NULL) {
        return OPRT_COM_ERROR;
    }

    *addr = ntohl(((struct in_addr *)(h->h_addr_list[0]))->s_addr);

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Bind to network with specified ip
 *
 * @param[in] fd: file descriptor
 * @param[in] ip: ip address
 *
 * @note This API is used for binding to network with specified ip.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_socket_bind(const int fd, const char *ip)
{
    // --- BEGIN: user implements ---
    struct sockaddr_in saddr = {0};

    if (ip == NULL) {
        return -3000;
    }

    saddr.sin_family = AF_INET;
    saddr.sin_addr.s_addr = inet_addr(ip);
    saddr.sin_port = 0;

    if (0 != bind(fd, (struct sockaddr*)&saddr, sizeof(saddr))) {
        return OPRT_MID_TRANSPORT_SOCK_NET_BIND_FAILED;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Set socket fd close mode
 *
 * @param[in] fd: file descriptor
 *
 * @note This API is used for setting socket fd close mode, the socket fd will not be closed in child processes
 * generated by fork calls.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_set_cloexec(const int fd)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED; // NOT support
    // --- END: user implements ---
}

/**
 * @brief Get ip address by socket fd
 *
 * @param[in] fd: file descriptor
 * @param[out] addr: ip address
 *
 * @note This API is used for getting ip address by socket fd.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_get_socket_ip(const int fd, TUYA_IP_ADDR_T *addr)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED;
    // --- END: user implements ---
}

/**
 * @brief Change ip string to address
 *
 * @param[in] ip_str: ip string
 *
 * @note This API is used to change ip string to address.
 *
 * @return ip address
 */
TUYA_IP_ADDR_T tkl_net_str2addr(const char *ip_str)
{
    // --- BEGIN: user implements ---
    if (ip_str == NULL) {
        return 0xFFFFFFFF;
    }

    TUYA_IP_ADDR_T addr1 = inet_addr((char *)ip_str);
    TUYA_IP_ADDR_T addr2 = ntohl(addr1);

    return addr2;
    // --- END: user implements ---
}

/**
 * @brief Change ip address to string
 *
 * @param[in] ipaddr: ip address
 *
 * @note This API is used to change ip address(in host byte order) to string(in IPv4 numbers-and-dots(xx.xx.xx.xx)
 * notion).
 *
 * @return ip string
 */
char *tkl_net_addr2str(const TUYA_IP_ADDR_T ipaddr)
{
    // --- BEGIN: user implements ---
    uint32_t addr = lwip_htonl(ipaddr);
    return ip_ntoa((ip_addr_t *) &addr);
    // --- END: user implements ---
}

/**
 * @brief Set socket options
 *
 * @param[in] fd: file descriptor
 * @param[in] level: setting level
 * @param[in] optname: the name of the option
 * @param[in] optval: the value of option
 * @param[in] optlen: the length of the option value
 *
 * @note This API is used for setting socket options.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_setsockopt(const int fd, const TUYA_OPT_LEVEL level, const TUYA_OPT_NAME optname,
                               const void *optval, const int optlen)
{
    // --- BEGIN: user implements ---
    return setsockopt(fd, level, optname, optval, optlen);
    // --- END: user implements ---
}

/**
 * @brief Get socket options
 *
 * @param[in] fd: file descriptor
 * @param[in] level: getting level
 * @param[in] optname: the name of the option
 * @param[out] optval: the value of option
 * @param[out] optlen: the length of the option value
 *
 * @note This API is used for getting socket options.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_getsockopt(const int fd, const TUYA_OPT_LEVEL level, const TUYA_OPT_NAME optname, void *optval,
                               int *optlen)
{
    // --- BEGIN: user implements ---
    return getsockopt(fd,(int)level,(int)optname,optval,(socklen_t *)optlen);
    // --- END: user implements ---
}

/**
 * @brief Set timeout option of socket fd
 *
 * @param[in] fd: file descriptor
 * @param[in] ms_timeout: timeout in ms
 * @param[in] type: transfer type, receive or send
 *
 * @note This API is used for setting timeout option of socket fd.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_set_timeout(const int fd, const int ms_timeout, const TUYA_TRANS_TYPE_E type)
{
    // --- BEGIN: user implements ---
    struct timeval timeout = {ms_timeout / 1000, (ms_timeout % 1000) * 1000};
    int optname = ((type == TRANS_RECV) ? SO_RCVTIMEO : SO_SNDTIMEO);

    if (setsockopt(fd, SOL_SOCKET, optname, &timeout, sizeof(timeout)) < 0) {
        return OPRT_MID_TRANSPORT_SOCK_SET_TIMEOUT_FAILED;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Set buffer_size option of socket fd
 *
 * @param[in] fd: file descriptor
 * @param[in] buf_size: buffer size in byte
 * @param[in] type: transfer type, receive or send
 *
 * @note This API is used for setting buffer_size option of socket fd.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_set_bufsize(const int fd, const int buf_size, const TUYA_TRANS_TYPE_E type)
{
    // --- BEGIN: user implements ---
    int size = buf_size;
    int optname = ((type == TRANS_RECV) ? SO_RCVBUF : SO_SNDBUF);

    if (setsockopt(fd, SOL_SOCKET, optname, (const char *)&size, sizeof(int)) < 0) {
        return OPRT_SET_SOCK_ERR;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Enable reuse option of socket fd
 *
 * @param[in] fd: file descriptor
 *
 * @note This API is used to enable reuse option of socket fd.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_set_reuse(const int fd)
{
    // --- BEGIN: user implements ---
    int reuse = 1;

    if (0 != setsockopt(fd, SOL_SOCKET, SO_REUSEADDR, (const char *)&reuse, sizeof(int))) {
        tkl_log_output("tkl_net_set_reuse err, fd(%d)!\r\n", fd);
        return OPRT_MID_TRANSPORT_SOCK_SET_REUSE_FAILED;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Disable nagle option of socket fd
 *
 * @param[in] fd: file descriptor
 *
 * @note This API is used to disable nagle option of socket fd.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_disable_nagle(const int fd)
{
    // --- BEGIN: user implements ---
    if (fd < 0) {
        return -3000 + fd;
    }

    int nodelay = 1;

    if (0 != setsockopt(fd, IPPROTO_TCP, TCP_NODELAY, (const char *)&nodelay, sizeof(int))) {
        return OPRT_MID_TRANSPORT_SOCK_SET_DISABLE_NAGLE_FAILED;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Enable broadcast option of socket fd
 *
 * @param[in] fd: file descriptor
 *
 * @note This API is used to enable broadcast option of socket fd.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_set_broadcast(const int fd)
{
    // --- BEGIN: user implements ---
    if (fd < 0) {
        return -3000 + fd;
    }

    int opt = 1;

    if (0 != setsockopt(fd, SOL_SOCKET, SO_BROADCAST, (const char *)&opt, sizeof(int))) {
        return OPRT_COM_ERROR;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Set keepalive option of socket fd to monitor the connection
 *
 * @param[in] fd: file descriptor
 * @param[in] alive: keepalive option, enable or disable option
 * @param[in] idle: keep idle option, if the connection has no data exchange with the idle time(in seconds), start
 * probe.
 * @param[in] intr: keep interval option, the probe time interval.
 * @param[in] cnt: keep count option, probe count.
 *
 * @note This API is used to set keepalive option of socket fd to monitor the connection.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_set_keepalive(int fd, const BOOL_T alive, const uint32_t idle, const uint32_t intr,
                                  const uint32_t cnt)
{
    // --- BEGIN: user implements ---
    if (fd < 0) {
        return -3000 + fd;
    }

    int ret = 0;
    int keepalive = alive;
    int keepidle = idle;
    int keepinterval = intr;
    int keepcount = cnt;

    ret |= setsockopt(fd, SOL_SOCKET, SO_KEEPALIVE, (void *)&keepalive, sizeof(keepalive));
    ret |= setsockopt(fd, IPPROTO_TCP, TCP_KEEPIDLE, (void*)&keepidle, sizeof(keepidle));
    ret |= setsockopt(fd, IPPROTO_TCP, TCP_KEEPINTVL, (void *)&keepinterval, sizeof(keepinterval));
    ret |= setsockopt(fd, IPPROTO_TCP, TCP_KEEPCNT, (void *)&keepcount, sizeof(keepcount));

    if(0 != ret) {
        return OPRT_SET_SOCK_ERR;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Get socket name
 *
 * @param[in] fd: file descriptor
 * @param[out] addr: ip address
 * @param[out] port: port information
 *
 * @note This API is used to Get the current name for the specified socket
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_getsockname(int fd, TUYA_IP_ADDR_T *addr, uint16_t *port)
{
    // --- BEGIN: user implements ---
    struct sockaddr_in saddr = {0};
    socklen_t len = sizeof(saddr);

    getsockname(fd, (struct sockaddr *)&saddr, &len);

    if (addr) {
        *addr = ntohl(saddr.sin_addr.s_addr);
    }

    if (port) {
        *port = ntohs(saddr.sin_port);
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Get name of connected peer socket
 *
 * @param[in] fd: file descriptor
 * @param[out] addr: ip address
 * @param[out] port: port information
 *
 * @note This API is used to Get the name of connected peer socket.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_getpeername(int fd, TUYA_IP_ADDR_T *addr, uint16_t *port)
{
    // --- BEGIN: user implements ---
    struct sockaddr_storage sa;
    socklen_t len = sizeof(sa);

    getpeername(fd, (struct sockaddr *)&sa, &len);

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief Set the system hostname
 *
 * @param[in] hostname: hostname to set
 *
 * @note This API is used to set the system hostname.
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_net_sethostname(const char *hostname)
{
    // --- BEGIN: user implements ---
    return OPRT_NOT_SUPPORTED; // not support LWIP_NETIF_HOSTNAME
    // --- END: user implements ---
}

