/**
 * @file tkl_gpio.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "gd32vw55x_gpio.h"
#include "gd32vw55x_rcu.h"
#include "tkl_gpio.h"
#include "tuya_error_code.h"
// --- END: user defines and implements ---

/* TUYA_GPIO_NUM_E is a common type shared by every platform, so TUYA_GPIO_NUM_MAX is
 * far larger than what this chip bonds out. GD32VW553 exposes 29 pins:
 * PA0-PA15, PB0-PB4, PB11-PB13, PB15, PC8, PC13-PC15. Anything above that must be
 * rejected at the API rather than indexing past the tables below. */
#define GD32_GPIO_NUM   29

typedef struct gpio_port {
    uint32_t gpio_group;
    uint32_t pin_num;
} gpio_port_t;

typedef struct {
    uint32_t            exti_line;
    uint8_t             is_irq;
    TUYA_GPIO_IRQ_CB    cb;
    void                *args;
} pin_dev_map_t;

static pin_dev_map_t gpio_pin_map[GD32_GPIO_NUM] = {
    // PA0-PA15
    {EXTI_0,  false, NULL, NULL}, {EXTI_1,  false, NULL, NULL},
    {EXTI_2,  false, NULL, NULL}, {EXTI_3,  false, NULL, NULL},
    {EXTI_4,  false, NULL, NULL}, {EXTI_5,  false, NULL, NULL},
    {EXTI_6,  false, NULL, NULL}, {EXTI_7,  false, NULL, NULL},
    {EXTI_8,  false, NULL, NULL}, {EXTI_9,  false, NULL, NULL},
    {EXTI_10, false, NULL, NULL}, {EXTI_11, false, NULL, NULL},
    {EXTI_12, false, NULL, NULL}, {EXTI_13, false, NULL, NULL},
    {EXTI_14, false, NULL, NULL}, {EXTI_15, false, NULL, NULL},
    // PB0-PB4
    {EXTI_0,  false, NULL, NULL}, {EXTI_1,  false, NULL, NULL},
    {EXTI_2,  false, NULL, NULL}, {EXTI_3,  false, NULL, NULL},
    {EXTI_4,  false, NULL, NULL},
    // PB11-PB13 & PB15 (PB14 not present on this chip)
    {EXTI_11, false, NULL, NULL}, {EXTI_12, false, NULL, NULL},
    {EXTI_13, false, NULL, NULL}, {EXTI_15, false, NULL, NULL},
    // PC8
    {EXTI_8,  false, NULL, NULL},
    // PC13
    {EXTI_13, false, NULL, NULL},
    // PC14 (unused)
    {EXTI_14, false, NULL, NULL},
    // PC15
    {EXTI_15, false, NULL, NULL},
};

void gpio_irq_hdl(uint32_t exti_line_num)
{
    uint8_t i;
    int index = 0;
    char exti_pin_num[] = {2, 2, 2, 2, 2, 6, 13};
    char exti_pin_index_map[7][13] = {{0, 16}, {1, 17}, {2, 18}, {3, 19}, {4, 20}, {5, 6, 7, 8, 9, 25},\
                                    {10, 11, 12, 13, 14, 15, 21, 22, 23, 24, 26, 27, 28}};
    if (exti_line_num >= sizeof(exti_pin_num)) {
        return;
    }

    for (i = 0; i < exti_pin_num[exti_line_num]; i++) {
        index = exti_pin_index_map[exti_line_num][i];

        if (RESET == exti_interrupt_flag_get(gpio_pin_map[index].exti_line)) {
            continue;
        }

        if (gpio_pin_map[index].is_irq && gpio_pin_map[index].cb) {
            gpio_pin_map[index].cb(gpio_pin_map[index].args);
        }

        /* Clear whether or not anyone is listening. The flag used to be cleared only
         * on the path that ran a callback, so a line still enabled in the EXTI after
         * its pin was released kept re-entering this handler for ever. */
        exti_interrupt_flag_clear(gpio_pin_map[index].exti_line);
    }
}

static int pin_id_2_gpio_port(TUYA_GPIO_NUM_E pin_id, struct gpio_port *port)
{
    if (pin_id >= TUYA_GPIO_NUM_0 && pin_id <= TUYA_GPIO_NUM_15) {          // PA0-PA15
        port->gpio_group = GPIOA;
        port->pin_num = BIT(pin_id);
    } else if (pin_id >= TUYA_GPIO_NUM_16 && pin_id <= TUYA_GPIO_NUM_20) {  // PB0-PB4
        port->gpio_group = GPIOB;
        port->pin_num = BIT((pin_id - 16));
    } else if (pin_id >= TUYA_GPIO_NUM_21 && pin_id <= TUYA_GPIO_NUM_24) {  // PB11-PB13 & PB15
        port->gpio_group = GPIOB;
        if (pin_id == TUYA_GPIO_NUM_24) {
            port->pin_num = GPIO_PIN_15;
        } else {
            port->pin_num = BIT((pin_id - 10));
        }
    } else if (pin_id >= TUYA_GPIO_NUM_25 && pin_id < GD32_GPIO_NUM) {  // PC8 & PC13 & PC15
        port->gpio_group = GPIOC;
        if (pin_id == TUYA_GPIO_NUM_25) {
            port->pin_num = GPIO_PIN_8;
        } else {
            port->pin_num = BIT((pin_id - 13));
        }
    } else {
        return -1;
    }

    return 0;
}

/**
 * @brief gpio init
 *
 * @param[in] pin_id: gpio pin id, id index starts at 0
 * @param[in] cfg:  gpio config
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_gpio_init(TUYA_GPIO_NUM_E pin_id, const TUYA_GPIO_BASE_CFG_T *cfg)
{
    // --- BEGIN: user implements ---
    struct gpio_port port;

    if (pin_id_2_gpio_port(pin_id, &port))
        return OPRT_INVALID_PARM;

    switch (port.gpio_group)
    {
    case GPIOA:
        rcu_periph_clock_enable(RCU_GPIOA);
        break;
    case GPIOB:
        rcu_periph_clock_enable(RCU_GPIOB);
        break;
    case GPIOC:
        rcu_periph_clock_enable(RCU_GPIOC);
        break;
    default:
        break;
    }

    switch (cfg->mode) {
    case TUYA_GPIO_PULLUP:            // for input
        gpio_mode_set(port.gpio_group, GPIO_MODE_INPUT, GPIO_PUPD_PULLUP, port.pin_num);
        break;
    case TUYA_GPIO_PULLDOWN:          // for input
        gpio_mode_set(port.gpio_group, GPIO_MODE_INPUT, GPIO_PUPD_PULLDOWN, port.pin_num);
        break;
    case TUYA_GPIO_FLOATING:          // for input
        gpio_mode_set(port.gpio_group, GPIO_MODE_INPUT, GPIO_PUPD_NONE, port.pin_num);
        break;
    case TUYA_GPIO_PUSH_PULL:         // for output
        gpio_mode_set(port.gpio_group, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, port.pin_num);
        gpio_output_options_set(port.gpio_group, GPIO_OTYPE_PP, GPIO_OSPEED_25MHZ, port.pin_num);
        break;
    case TUYA_GPIO_OPENDRAIN:         // for output
        gpio_mode_set(port.gpio_group, GPIO_MODE_OUTPUT, GPIO_PUPD_NONE, port.pin_num);
        gpio_output_options_set(port.gpio_group, GPIO_OTYPE_OD, GPIO_OSPEED_25MHZ, port.pin_num);
        break;
    case TUYA_GPIO_OPENDRAIN_PULLUP:  // for output
        /* was identical to TUYA_GPIO_OPENDRAIN - the internal pull-up never got
         * enabled, so an open-drain line had nothing to pull it back high */
        gpio_mode_set(port.gpio_group, GPIO_MODE_OUTPUT, GPIO_PUPD_PULLUP, port.pin_num);
        gpio_output_options_set(port.gpio_group, GPIO_OTYPE_OD, GPIO_OSPEED_25MHZ, port.pin_num);
        break;
    case TUYA_GPIO_HIGH_IMPEDANCE:
        /* Two things were wrong here. The pin was put in open-drain *output* with a
         * pull-up, which loads the line rather than letting go of it, and the case had
         * no break, so it fell into default and reported failure even after doing the
         * work. Analog mode is the real high impedance state: the input buffer is off,
         * no pull is applied, and leakage is at its lowest. */
        gpio_mode_set(port.gpio_group, GPIO_MODE_ANALOG, GPIO_PUPD_NONE, port.pin_num);
        break;
    default:
        return OPRT_INVALID_PARM;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief gpio deinit
 *
 * @param[in] pin_id: gpio pin id, id index starts at 0
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_gpio_deinit(TUYA_GPIO_NUM_E pin_id)
{
    // --- BEGIN: user implements ---
    if (pin_id >= GD32_GPIO_NUM)
        return OPRT_INVALID_PARM;

    if (gpio_pin_map[pin_id].is_irq == true) {
        /* Silence the line in hardware too. Forgetting the callback while leaving the
         * EXTI armed left the interrupt firing into a handler that no longer had
         * anything to do with it. */
        exti_interrupt_disable(gpio_pin_map[pin_id].exti_line);
        exti_interrupt_flag_clear(gpio_pin_map[pin_id].exti_line);

        gpio_pin_map[pin_id].is_irq = false;
        gpio_pin_map[pin_id].args = NULL;
        gpio_pin_map[pin_id].cb = NULL;
    }

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief gpio write
 *
 * @param[in] pin_id: gpio pin id, id index starts at 0
 * @param[in] level: gpio output level value
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_gpio_write(TUYA_GPIO_NUM_E pin_id, TUYA_GPIO_LEVEL_E level)
{
    // --- BEGIN: user implements ---
    struct gpio_port port;

    if (pin_id_2_gpio_port(pin_id, &port))
        return OPRT_INVALID_PARM;

    gpio_bit_write(port.gpio_group, port.pin_num, (FlagStatus)level);
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief gpio read
 *
 * @param[in] pin_id: gpio pin id, id index starts at 0
 * @param[out] level: gpio output level
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_gpio_read(TUYA_GPIO_NUM_E pin_id, TUYA_GPIO_LEVEL_E *level)
{
    // --- BEGIN: user implements ---
    struct gpio_port port;

    if (pin_id_2_gpio_port(pin_id, &port))
        return OPRT_INVALID_PARM;

    *level = (TUYA_GPIO_LEVEL_E)gpio_input_bit_get(port.gpio_group, port.pin_num);
    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief gpio irq init
 * NOTE: call this API will not enable interrupt
 *
 * @param[in] pin_id: gpio pin id, id index starts at 0
 * @param[in] cfg:  gpio irq config
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_gpio_irq_init(TUYA_GPIO_NUM_E pin_id, const TUYA_GPIO_IRQ_T *cfg)
{
    struct gpio_port port;

    if (pin_id_2_gpio_port(pin_id, &port))
        return OPRT_INVALID_PARM;

    /* Bias the line away from the edge being waited for, otherwise that edge can never
     * happen. This used to be a hardcoded pull-up, which pinned an active-high input
     * high for good and made TUYA_GPIO_IRQ_RISE impossible to trigger. */
    switch (cfg->mode) {
    case TUYA_GPIO_IRQ_RISE:
    case TUYA_GPIO_IRQ_HIGH:
        gpio_mode_set(port.gpio_group, GPIO_MODE_INPUT, GPIO_PUPD_PULLDOWN, port.pin_num);
        break;
    case TUYA_GPIO_IRQ_FALL:
    case TUYA_GPIO_IRQ_LOW:
        gpio_mode_set(port.gpio_group, GPIO_MODE_INPUT, GPIO_PUPD_PULLUP, port.pin_num);
        break;
    case TUYA_GPIO_IRQ_RISE_FALL:
    default:
        /* both edges matter, so let the external circuit decide the idle level */
        gpio_mode_set(port.gpio_group, GPIO_MODE_INPUT, GPIO_PUPD_NONE, port.pin_num);
        break;
    }

    rcu_periph_clock_enable(RCU_SYSCFG);

    switch (port.gpio_group)
    {
    case GPIOA:
        syscfg_exti_line_config(EXTI_SOURCE_GPIOA, (31 - __CLZ(port.pin_num)));
        break;
    case GPIOB:
        syscfg_exti_line_config(EXTI_SOURCE_GPIOB, (31 - __CLZ(port.pin_num)));
        break;
    case GPIOC:
        syscfg_exti_line_config(EXTI_SOURCE_GPIOC, (31 - __CLZ(port.pin_num)));
        break;
    default:
        break;
    }

    switch (cfg->mode)
    {
    case TUYA_GPIO_IRQ_RISE:
        exti_init(gpio_pin_map[pin_id].exti_line, EXTI_INTERRUPT, EXTI_TRIG_RISING);
        break;
    case TUYA_GPIO_IRQ_FALL:
        exti_init(gpio_pin_map[pin_id].exti_line, EXTI_INTERRUPT, EXTI_TRIG_FALLING);
        break;
    case TUYA_GPIO_IRQ_RISE_FALL:
        exti_init(gpio_pin_map[pin_id].exti_line, EXTI_INTERRUPT, EXTI_TRIG_BOTH);
        break;
    case TUYA_GPIO_IRQ_LOW:
    case TUYA_GPIO_IRQ_HIGH:
    default:
        return OPRT_INVALID_PARM;
    }

    gpio_pin_map[pin_id].args = cfg->arg;
    gpio_pin_map[pin_id].cb = cfg->cb;
    gpio_pin_map[pin_id].is_irq = true;

    return OPRT_OK;
}

/**
 * @brief gpio irq enable
 *
 * @param[in] pin_id: gpio pin id, id index starts at 0
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_gpio_irq_enable(TUYA_GPIO_NUM_E pin_id)
{
    // --- BEGIN: user implements ---
    if (pin_id >= GD32_GPIO_NUM)
        return OPRT_INVALID_PARM;

    if (gpio_pin_map[pin_id].is_irq == false)
        return OPRT_INVALID_PARM;

    switch (gpio_pin_map[pin_id].exti_line)
    {
    case EXTI_0:
        eclic_irq_enable(EXTI0_IRQn, 8, 0);
        break;
    case EXTI_1:
        eclic_irq_enable(EXTI1_IRQn, 8, 0);
        break;
    case EXTI_2:
        eclic_irq_enable(EXTI2_IRQn, 8, 0);
        break;
    case EXTI_3:
        eclic_irq_enable(EXTI3_IRQn, 8, 0);
        break;
    case EXTI_4:
        eclic_irq_enable(EXTI4_IRQn, 8, 0);
        break;
    case EXTI_5 ... EXTI_9:
        eclic_irq_enable(EXTI5_9_IRQn, 8, 0);
        break;
    case EXTI_10 ... EXTI_15:
        eclic_irq_enable(EXTI10_15_IRQn, 8, 0);
        break;
    default:
        return OPRT_INVALID_PARM;
    }

    exti_interrupt_flag_clear(gpio_pin_map[pin_id].exti_line);
    exti_interrupt_enable(gpio_pin_map[pin_id].exti_line);

    return OPRT_OK;
    // --- END: user implements ---
}

/**
 * @brief gpio irq disable
 *
 * @param[in] pin_id: gpio pin id, id index starts at 0
 *
 * @return OPRT_OK on success. Others on error, please refer to tuya_error_code.h
 */
OPERATE_RET tkl_gpio_irq_disable(TUYA_GPIO_NUM_E pin_id)
{
    // --- BEGIN: user implements ---
    if (pin_id >= GD32_GPIO_NUM)
        return OPRT_INVALID_PARM;

    /* Mask this line only. Lines 5..9 and 10..15 share one interrupt vector between
     * them, so switching the vector off - which is what this used to do - silenced
     * every other pin in the same group as collateral damage. */
    exti_interrupt_disable(gpio_pin_map[pin_id].exti_line);
    exti_interrupt_flag_clear(gpio_pin_map[pin_id].exti_line);

    return OPRT_OK;
    // --- END: user implements ---
}
