/**
 * @file tkl_lwip.c
 * @brief this file was auto-generated by tuyaos v&v tools, developer can add implements between BEGIN and END
 *
 * @warning: changes between user 'BEGIN' and 'END' will be keeped when run tuyaos v&v tools
 *           changes in other place will be overwrited and lost
 *
 * @copyright Copyright 2020-2021 Tuya Inc. All Rights Reserved.
 *
 */

// --- BEGIN: user defines and implements ---
#include "lwip/netif.h"
#include "tkl_lwip.h"
#include "tuya_error_code.h"
// --- END: user defines and implements ---

/**
 * @brief ethernet interface hardware init
 *
 * @param[in]      netif     the netif to which to send the packet
 * @return  err_t  SEE "err_enum_t" in "lwip/err.h" to see the lwip err(ERR_OK: SUCCESS other:fail)
 */
OPERATE_RET tkl_ethernetif_init(TKL_NETIF_HANDLE netif)
{
    // --- BEGIN: user implements ---
    struct netif *net_if = (struct netif *)netif;

    net_if->flags |= NETIF_FLAG_LINK_UP;

    return ERR_OK;
    // --- END: user implements ---
}

/**
 * @brief ethernet interface sendout the pbuf packet
 *
 * @param[in]      netif     the netif to which to send the packet
 * @param[in]      p         the packet to be send, in pbuf mode
 * @return  err_t  SEE "err_enum_t" in "lwip/err.h" to see the lwip err(ERR_OK: SUCCESS other:fail)
 */
OPERATE_RET tkl_ethernetif_output(TKL_NETIF_HANDLE netif, TKL_PBUF_HANDLE p)
{
    // --- BEGIN: user implements ---
    struct pbuf* p_buf = (struct pbuf*)p;
    struct netif *net_if = (struct netif *)netif;

    if (net_if->linkoutput(net_if, p_buf))
    {
        return -1;
    }

    return 0;
    // --- END: user implements ---
}

/**
 * @brief ethernet interface recv the packet
 *
 * @param[in]      netif       the netif to which to recieve the packet
 * @param[in]      total_len   the length of the packet recieved from the netif
 * @return  void
 */
OPERATE_RET tkl_ethernetif_recv(TKL_NETIF_HANDLE netif, TKL_PBUF_HANDLE p)
{
    // --- BEGIN: user implements ---
    struct pbuf* p_buf = (struct pbuf*)p;
    struct netif *net_if = (struct netif *)netif;

    if (net_if->input(p_buf, net_if))
    {
        return -1;
    }

    return 0;

    // --- END: user implements ---
}

